Document: fonts-gb
Title: Debian fonts-gb Manual
Author: <insert document author here>
Abstract: This manual describes what fonts-gb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fonts-gb/fonts-gb.sgml.gz

Format: postscript
Files: /usr/share/doc/fonts-gb/fonts-gb.ps.gz

Format: text
Files: /usr/share/doc/fonts-gb/fonts-gb.text.gz

Format: HTML
Index: /usr/share/doc/fonts-gb/html/index.html
Files: /usr/share/doc/fonts-gb/html/*.html
